config/routes.rb
Org::Application.routes.draw do
  devise_for :users

  root :to => "messages#index"
  resources :messages

  resources :categories

  resources :subjects

  resources :addresses

  resources :organizations

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :address
  belongs_to :subject
  belongs_to :category
  belongs_to :user
  attr_accessible :body, :train, :address_id, :category_id, :subject_id, :user_id, :assigned_category
  accepts_nested_attributes_for :category, :reject_if => :all_blank
  #after_commit :classify




  def classify
    if self.user.trained == true
      if self.train == false
        tr = ""
        tr << self.body + ' ' + self.subject.title + ' ' + self.address.from + ' ' + self.address.organization.title
        assig = self.user.classifier.classify tr
        self.update_attribute(:assigned_category, assig)
      end
    end
  end

    searchable do
    text :body, :stored => true do |mes|
      mes.body + mes.address.from + mes.subject.title + mes.address.organization.title
    end
    text :title, :stored => true do |t|
      t.subject.title + ' ' + t.address.organization.title
    end
  end





end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  #before_filter :authenticate_user!

  def index
    @messages = if params[:q].blank?
      Message.all.paginate(:per_page => 30, :page => params[:page])
  else
   poisk = Message.search(:include => [:address, :category, :subject]) do |s|
      s.keywords params[:q], :highlight => true, :merge_continuous_fragments => true, :phrase_fields => {:title => 3.0, :from => 1.5}
    end
    poisk.results
    end
  @total_hits = poisk.total if poisk
  @total_messages = Message.all.length.to_s
  calc_properly

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end

  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end

  def search1
    @search = Message.search(:include => [:address, :category, :subject, :organization]) do
      keywords[params[:q]]
    end
  end

  private
  def calc_properly
    @cl_result = 0
  Message.all.each do |mes|
    if mes.assigned_category.downcase == mes.category.title.downcase
      @cl_result += 1
    end
  end

  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
  <div class="group">
    <%= f.label :body, t("activerecord.attributes.message.body", :default => "Body"), :class => :label %>
    <%= f.text_area :body, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :train, t("activerecord.attributes.message.train", :default => "Train"), :class => :label %>
    <%= f.check_box :train, :class => 'check_box' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :address_id, t("activerecord.attributes.message.address_id", :default => "Address"), :class => :label %>
    <%= f.text_field :address_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :category_id, t("activerecord.attributes.message.category_id", :default => "Category"), :class => :label %>
    <%= f.text_field :category_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :subject_id, t("activerecord.attributes.message.subject_id", :default => "Subject"), :class => :label %>
    <%= f.text_field :subject_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), messages_path, :class => "text_button_padding link_button" %>
</div>

app/views/messages/_sidebar.html.erb
<div class="block notice">
  <h3>Statistics</h3>
  <div class="content">
    <p>Number of properly classified messages: <%= @cl_result %></p>
    <p>Number of messages: <%= @total_messages %></p>
    <% if @total_hits %>
    <p>Documents found: <%= @total_hits %>
    <% end %>
  </div>
</div>
<div class="block">
  <h3>Info</h3>
  <ul class="navigation">
    <li><a href="http://www.tue.nl">TU/e</a></li>
  </ul>
</div>

app/views/messages/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", messages_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_message_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_message_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Message</h2>
    <div class="inner">
      <%= form_for @message, :url => message_path(@message), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/messages/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", messages_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_message_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Messages</h2>
    <%= form_tag messages_path, :method => :get do %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Search" %>
    <% end %>

    <div class="inner">
      <table class="table">
      <% unless !@messages%>
        <tr>
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.message.body", :default => t("activerecord.labels.body", :default => "Body")) %>
          </th>
                    <th>
                    Category
                    </th>
                    <th>
                    Assigned category
                    </th>

        </tr>
        <% @messages.each do |message| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= message.id %>
          </td>
           <td>
            <%= link_to message.body[0..150], message_path(message) %>
          </td>

          </td>
          <td>
          <%= message.category.title %>
          </td>
          <td>
          <%= message.assigned_category.downcase %>
          </td>

            <%#= link_to "#{t("web-app-theme.show", :default => "Show")}", message_path(message) %>
            <%#= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_message_path(message) %>
            <%#= link_to "#{t("web-app-theme.delete", :default => "Delete")}", message_path(message), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>

        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>

        <%= will_paginate @messages  %>

      </div>
    </div>
    <% end %>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/messages/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", messages_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_message_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Message</h2>
    <div class="inner">
      <%= form_for :message, :url => messages_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/messages/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", messages_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_message_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", message_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">

        <p>
          <b><%= t("activerecord.attributes.message.body", :default => t("activerecord.labels.body", :default => "Body")) %>:</b>
          <%= @message.body %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.message.train", :default => t("activerecord.labels.train", :default => "Train")) %>:</b>
          <%= @message.train %>
        </p>


        <p>
          <b><%= t("activerecord.attributes.message.address_id", :default => t("activerecord.labels.address_id", :default => "Address")) %>:</b>
          <%= @message.address.from %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.message.category_id", :default => t("activerecord.labels.category_id", :default => "Category")) %>:</b>
          <%= @message.category.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.message.subject_id", :default => t("activerecord.labels.subject_id", :default => "Subject")) %>:</b>
          <%= @message.subject.title %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_message_path(@message), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), message_path(@message), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>